Rename Python files to have .py extension
freedomofpress/securedrop-workstation pull request #1019
Opened 2024-05-03 19:46 UTC by micahflee

## Status

Ready for review

## Description of Changes

Fixes #1003.

Changes proposed in this pull request:

I've renamed these files to end in `.py`:

- `dom0/remove-tags`
- `files/destroy-vm`
- `files/sdw-login`
- `files/sdw-notify`
- `files/sdw-updater`
- `scripts/configure-environment`

And I also searched the rest of the code for these filenames and updated the new filenames where appropriate.

The dom0 tests all seem to pass. Please review carefully though because I'm not sure what if anything I should be testing manually to make sure this didn't break anything.

## Testing

If you made non-trivial code changes, include a test plan and validated it for this PR.

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing pilot instances
2. New installs

## Checklist

### If you have made changes to the provisioning logic

- [x] All tests (`make test`) pass in `dom0`

### If you have added or removed files

- [x] I have updated `MANIFEST.in` and `rpm-build/SPECS/securedrop-workstation-dom0-config.spec`

2024-05-03 21:24 UTC, legoktm requested changes
Thanks! Can we have the files be installed using the same names they currently have? For example, `sdw-admin.py` is installed as `sdw-admin` using:
```spec
install -m 755 files/sdw-admin.py %{buildroot}/%{_bindir}/sdw-admin
```

That way it's a no-op on a deployed system.

2024-05-03 21:24 UTC, legoktm commented on .flake8
>      *.py
Can the explicit `*.py` be dropped now? I assume it's the default...

2024-05-07 00:48 UTC, micahflee commented
Okay, I've made those changes and this should be good for another review @legoktm

2024-05-07 15:25 UTC, legoktm approved these changes
LGTM! I'm going to squash this and merge

2024-05-07 15:25 UTC, legoktm commented on pyproject.toml
>      "dom0/securedrop-login",
This seems to be gone now, we can remove it in a follow-up.

2024-05-07 15:28 UTC, legoktm approved these changes

2024-05-07 15:33 UTC, merged