Update readme to include information about new repo structure
freedomofpress/securedrop-workstation pull request #1072
Opened 2024-06-06 15:52 UTC by rocodes

## Status

Ready for review

## Description of Changes

Update README "What's in this repo" section

Changes proposed in this pull request:

readme-only 

## Testing

- [ ] Visual/content review plz
- [ ] lint is happy 

## Deployment

Any special considerations for deployment? Consider both:

1. Upgrading existing pilot instances
2. New installs

## Checklist

### If you have made changes to the provisioning logic

- [ ] All tests (`make test`) pass in `dom0`

### If you have added or removed files

- [ ] I have updated `MANIFEST.in` and `rpm-build/SPECS/securedrop-workstation-dom0-config.spec`

### If documentation is required

- [ ] I have opened a PR in the [docs repo](https://github.com/freedomofpress/securedrop-workstation-docs) for these changes, or will do so later
- [ ] I would appreciate help with the documentation

2024-06-06 17:02 UTC, zenmonkeykstop requested changes
Some suggestions for edits but overall great, thanks for grabbing this!

2024-06-06 17:02 UTC, zenmonkeykstop commented on README.md
>  - `sd-journalist.sec.example` is an example GPG private key for use in decrypting submissions. It must match the public key set on a SecureDrop server used for testing. Before use, you should copy it
I'd be stronger here and say something like "it is the public key component of the GPG keypair used in testing and development of SecureDrop - this keypair must not be used in a production environment." Maybe less grumpily.

2024-06-06 17:02 UTC, zenmonkeykstop commented on README.md
> +- There are other components as well: the *SecureDrop Client* opens all submissions in the `sd-viewer` disposable VM; and a logging VM, `sd-log`, is provisioned to capture logs locally from various p
You could just enumerate these components separately in the same way as the previous two, they have their own (meta)packages etc even if they're not as complex.

2024-06-10 23:00 UTC, rocodes commented
@zenmonkeykstop addressed feedback in https://github.com/freedomofpress/securedrop-workstation/pull/1072/commits/f0bea6e848d020e6eaafdf56fa9746904c223183

2024-06-10 23:53 UTC, rocodes commented
CI is unrelated

2024-06-17 21:48 UTC, zenmonkeykstop approved these changes
LGTM

2024-06-17 21:50 UTC, merged