Improve sd-gpg test
freedomofpress/securedrop-workstation pull request #1085
Opened 2024-06-17 21:21 UTC by legoktm

## Status

Ready for review

## Description of Changes

* Verify the fingerprints match the configured one
* Simplify regex to parse GPG output (--fingerprint made it harder!)
* Verify only one secret key is present in the keyring

## Testing

* [ ] CI passed
* [ ] Visual review

## Deployment

Any special considerations for deployment? n/a

## Checklist

- [ ] All tests (`make test`) pass in `dom0`

2024-06-18 00:17 UTC, cfm requested changes
The revised test looks great.  I've left some nits to clarify some inline documentation that I found clouded rather than explained the test logic.  The distinction that I think is worthwhile is between the *fingerprint configured* somewhere versus the *key present* somewhere.

2024-06-18 00:17 UTC, cfm commented on tests/test_gpg.py
> +        self.fingerprint = self.dom0_config["submission_key_fpr"]
```suggestion
        # Obtain the fingerprint explicitly configured in dom0 and injected into VMs.
        self.fingerprint = self.dom0_config["submission_key_fpr"]
```

2024-06-18 00:17 UTC, cfm commented on tests/test_gpg.py
>          Obtain fingerprint for the key configured in dom0
```suggestion
        Obtain the fingerprint of the key actually present in dom0.
```

2024-06-18 00:17 UTC, cfm commented on tests/test_gpg.py
>          Obtain fingerprints for all keys configured in GPG VM
```suggestion
        Obtain fingerprints for all keys actually present in GPG VM
```

2024-06-18 00:17 UTC, cfm commented on tests/test_gpg.py
> +        """Verify the key in dom0 and sd-gpg match config.json"""
```suggestion
        """Verify the key present in dom0 and sd-gpg matches what's configured in config.json"""
```

2024-06-18 17:11 UTC, legoktm commented
Thanks, I've squashed in all your documentation suggestions.

2024-06-25 01:50 UTC, cfm approved these changes
Thanks, @legoktm.

2024-06-25 01:52 UTC, merged