Update lookup path for Notify.py script
freedomofpress/securedrop-workstation pull request #1108
Opened 2024-06-27 00:43 UTC by eloquence

Fixes #1107

## Status

Ready for review 
## Description of Changes

Updates outdated path.

## Testing

1. Ensure that `.securedrop_updater/sdw-last-updated` is set to a recent date like `2024-06-26 18:00:00` (you can fake it 😎)
2. Run `sdw-notify` in `dom0` without the change in this branch 
3. - [ ] Confirm that a warning appears despite the up-to-date goodness
4. Run `sdw-notify` with the change in this branch
5. - [ ] Confirm that no warning appears

2024-06-27 16:27 UTC, legoktm requested changes
This path is already in sdw_util, could we just import it from there so it's specified in just one place?

Also it needs updating in `sd-clean-all.sls` too.

2024-06-27 21:27 UTC, eloquence commented
(Pushed the `sd-clean-all` change)

2024-06-28 14:44 UTC, rocodes approved these changes

2024-06-28 17:39 UTC, legoktm approved these changes
Hm, is it also needing my re-approval to kick off the merge?

2024-06-28 17:41 UTC, merged