Bullseye nightlies
freedomofpress/securedrop-workstation pull request #783
Opened 2022-06-09 22:31 UTC by legoktm

## Status

Ready for review

## Description of Changes

* `make dev` now installs with nightlies ("nightlies" component on apt-test)
* use `qa-switch.sh` to switch to release candidates ("main" component on apt-test)
* re-run `make dev` to switch back

This was done by pairing with @cfm.

## Testing

* Follow the steps outlined above. In between each step check `/etc/apt/sources.list.d/securedrop_workstation.list` to see the correct component is being used. (note that you might need to manually restart appVMs to see the templateVM change take effect)
* The first commit can be tested with buster or bullseye, while the second requires the bullseye template etc. to be available.

## Deployment

Any special considerations for deployment? Should be a no-op for prod instances.

## Checklist

- [ ] All tests (`make test`) pass in `dom0`
- [x] I would appreciate help with the documentation

2022-06-09 23:15 UTC, cfm commented
Thanks, @legoktm!  I'll pick this up on Monday for review on fresh Qubes 4.1.  (`Co-authored-by` is generous; really I just happened to be in the room at the time. ;-)

2022-06-13 23:37 UTC, cfm requested changes
Partial test with partial prerequisites:
    
> - [x] The first commit can be tested with buster or bullseye
> - [ ] while the [second requires the bullseye template etc. to be available](https://github.com/freedomofpress/securedrop-workstation/pull/783/commits/f523cb60691dba4612d2191d5c89dad87874058f).

## First `make dev`

Once `fedora-35` has been installed, several states fail with:

```
qvm-clone: error: no such domain: 'fedora-35-dvm'
```
    
## Second `make dev`

Can observe `fedora-35-dvm` being created.  Failed due to needing to reapply <https://forum.qubes-os.org/t/ax210-211-wifi-card-not-showing-any-networks/9498/11> in `fedora-35` once the basis for `sys-net`.

## Third `make dev`

`/usr/share/securedrop-workstation-dom0-config/scripts/provision-all` fails with:

```sh-session
            ID: sd-viewer-install-metapackage
      Function: pkg.installed
        Result: False
       Comment: Problem encountered installing package(s). Additional info follows:
                
                errors:
                    - Running scope as unit: run-r4899b96ecf4c4affbae0fe312d932722.scope
                      E: Unable to locate package securedrop-workstation-viewer
       Started: 15:47:25.014850
      Duration: 816.879 ms
       Changes:
```

- [x] `securedrop-debian-packaging` is missing a CircleCI job to build the `securedrop-workstation-viewer` nightly.  → freedomofpress/securedrop-debian-packaging#342

* [x] Follow the steps outlined above. In between each step check `/etc/apt/sources.list.d/securedrop_workstation.list` to see the correct component is being used. (note that you might need to manually restart appVMs to see the templateVM change take effect)

```sh-session
[cfm@dom0 securedrop-workstation]$ qvm-run --pass-io sd-large-buster-template "cat /etc/apt/sources.list.d/securedrop_workstation.list"
deb [arch=amd64] https://apt-test.freedom.press/ buster nightlies
[cfm@dom0 securedrop-workstation]$ qvm-run --pass-io sd-small-buster-template "cat /etc/apt/sources.list.d/securedrop_workstation.list"
deb [arch=amd64] https://apt-test.freedom.press/ buster nightlies
```

## Next steps

- [x] freedomofpress/securedrop-debian-packaging#342
- [ ] Will plan to retest tomorrow afternoon (Pacific) with `f32` bullseye template once available.

2022-06-14 01:37 UTC, creviera commented
## Next steps

- [x] https://github.com/freedomofpress/securedrop-debian-packaging/pull/342
- [ ] Will plan to retest tomorrow afternoon (Pacific) with f32 bullseye template once available. 

Regarding this last step: once https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/34 is merged, the `qubes-template-securedrop-workstation` package will get added to `yum-test` and you should be able to do your final check as part of this PR's test plan.

2022-06-14 20:52 UTC, cfm requested changes
> - [x] The first commit can be tested with buster or bullseye
> - [x] while the [second requires the bullseye template etc. to be available](https://github.com/freedomofpress/securedrop-workstation/pull/783/commits/f523cb60691dba4612d2191d5c89dad87874058f).

As of f523cb60691dba4612d2191d5c89dad87874058f, with all `buster nightlies` available, `make dev` passes.  However, even with the `f32` bullseye template *available*, we can't meaningfully test `./qa-switch.sh` until `make dev` *installs from* `bullseye nightlies`.  Conferring with @eaon about how to converge these two efforts.

2022-06-15 01:01 UTC, eaon commented
After discussing this with all involved parties, because of the work that is still required to make SDW on 4.1 use bullseye templates, we opted to take the first commit of this PR and leave the `qa-switch` work behind. This PR is superseded by #784

2022-06-15 01:01 UTC, closed without merging